### ISSUE TITLE
Weird artifacts when using OverlayImageLayer

### ISSUE THREAD

**Issue by Phil9l** [greensopinion/flutter-vector-map-tiles#102]
I face a strange problem which I don't really understand how to debug.

When I use `VectorTileLayer` + `OverlayImageLayer` I often get weird artifacts.

As I noticed it happens only with zoom being between 22 and 23 (even though I don't have these constants anywhere in my code). Reproducible in both release and debug.

If I scroll to the part of the map which doesn't contain `OverlayImageLayer` then I can't reproduce it.

Without `VectorTileLayer` I don't see this issue but maybe I didn't try enough.

It happens both when I move the map and when I just click on it (`onTap` is called, `onPositionChanged` not).

Examples: https://imgur.com/a/eQXY5fL (there are a few screenshots + videos).

It is reproducible with local asset image and with networkimage, with jpeg and png. I can reproduce it with `MemoryCacheVectorTileProvider` and with pure `NetworkVectorTileProvider`, doesn't depend on `maxZoom` property.

Changing theme or asset provider also doesn't help.

It seems to be fine on web and android emulator.

Code:
```
          FlutterMap(
            mapController: mapController,
            options: MapOptions(
              onPositionChanged: (MapPosition position, bool hasGesture) {
                print('PC');
                rotationAngle.value = degreeToRadian(mapController.rotation);
              },
              onTap: (position, latLng) {
                debugPrint('Clicked on map at ${latLng.latitude}, ${latLng.longitude}');
                print(mapController.zoom);
              },
              center: widget.venueDetails.location,
              zoom: 20,
              maxZoom: 26,
              minZoom: 17,
              absorbPanEventsOnScrollables: false,
              interactiveFlags: InteractiveFlag.drag |
                  InteractiveFlag.flingAnimation |
                  InteractiveFlag.pinchMove |
                  InteractiveFlag.pinchZoom |
                  InteractiveFlag.doubleTapZoom |
                  InteractiveFlag.rotate,
            ),
            children: [
              if (!kIsWeb)
                VectorTileLayer(
                  theme: _mapTheme(context),
                  tileProviders: TileProviders(
                    {
                      "openmaptiles": _cachingTileProvider(
                        _urlTemplate(),
                      ),
                    },
                  ),
                ),
              OverlayImageLayer(
                overlayImages: [
                    RotatedOverlayImage(
                      // imageProvider: CachedNetworkImageProvider(imageUrl),
                      imageProvider: AssetImage('assets/images/test.jpeg'),
                      topLeftCorner: widget.corners.topLeft,
                      bottomLeftCorner: widget.corners.bottomLeft,
                      bottomRightCorner: widget.corners.bottomRight,
                    ),
                ],
              ),
              // Some markers
            ],
          );

```

My flutter doctor is:
```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.30, on Debian GNU/Linux rodete 5.19.11-1rodete1-amd64, locale en_US.utf8)
    • Flutter version 3.7.0-3.0.pre.30 on channel master at ~/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0a8e92a119 (12 hours ago), 2022-12-05 17:40:10 -0500
    • Engine revision d82c8ad7ac
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ~/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /opt/android-studio-2021.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6-2
    • cmake version 3.24.2
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio-with-blaze-2021.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /opt/intellij-ue-2021.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 6 Pro (mobile)
    • Linux (desktop)      • linux          • linux-x64      • Debian GNU/Linux rodete 5.19.11-1rodete1-amd64
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Dependencies:
```
  flutter_map:
    dependency: "direct main"
    description:
      name: flutter_map
      sha256: "95e2b3ae37733c3da79aac6e5a245a524113d652d8e22bc5a5230d61d6db0175"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  flutter_map_dragmarker:
    dependency: "direct main"
    description:
      name: flutter_map_dragmarker
      sha256: "1a28bc1d1573bfca21c47a7d3fe3513a6587eea969d5aaabc1e4101c79f4e834"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  flutter_map_marker_cluster:
    dependency: "direct main"
    description:
      name: flutter_map_marker_cluster
      sha256: a272a9f79ec4964272646a5ecad26108040ac2f489e58f1a28d67069b341c3f0
      url: "https://pub.dev"
    source: hosted
    version: "1.0.1"
  flutter_map_marker_popup:
    dependency: transitive
    description:
      name: flutter_map_marker_popup
      sha256: "9eb13384fb217d446398f8de484a70d668ab986485ce75bb3adf5e853a1d8b8a"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  vector_map_tiles:
    dependency: "direct main"
    description:
      name: vector_map_tiles
      sha256: a0411b32ec4a8b548eb2fdf74d0e1165310e86415c3a7a26459cedf0d4fd1bc0
      url: "https://pub.dev"
    source: hosted
    version: "3.1.4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  vector_tile:
    dependency: transitive
    description:
      name: vector_tile
      sha256: "2ac77f6bbd7ddd97efe059207d67bb7eaf807ab98ad58d99fe41a22c230f44e1"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  vector_tile_renderer:
    dependency: "direct main"
    description:
      name: vector_tile_renderer
      sha256: "1d4c60b5d8e73b5d8286516f10b02880e3e51156fd2bb82ba2c1f3201e38b89e"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.4"
```
